# Generated by Django 3.2.7 on 2021-10-04 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataCartaz', models.DateTimeField(verbose_name='Data do Cartaz')),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.CharField(max_length=16, verbose_name='Produto')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assento', models.IntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=16)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=16, verbose_name='Nome')),
                ('sinopse', models.CharField(max_length=128, verbose_name='Sinopse')),
                ('categoria', models.CharField(max_length=32, verbose_name='Categoria')),
                ('classificacao', models.CharField(max_length=8, verbose_name='Classificação')),
                ('duracao', models.CharField(max_length=16, verbose_name='Duração')),
                ('capa', stdimage.models.StdImageField(upload_to='imagens', verbose_name='Capa do Filme')),
                ('cartaz', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aplicativo.cartaz')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=32, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=32, verbose_name='Email')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
