# Generated by Django 3.2.7 on 2021-09-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='classificacao',
            field=models.CharField(max_length=10, verbose_name='Classificação'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='duracao',
            field=models.CharField(max_length=30, verbose_name='Duração'),
        ),
    ]
